### ISSUE TITLE
pip install -r requirements/prod.txt

### ISSUE THREAD

**Issue by BillCorey** [mwolff44/pyfreebilling#102]
This command
python manage.py migrate

is generating errors on my machine. Can't get past this point. 
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named debug_toolbar

I don't see any django_setup() procedure inside /django/core/management/__init__.py

Why all these errors? Is there an update or bug fix?

**Comment by mwolff44** [comment]
did you create the file locals.py ?

**Comment by mwolff44** [comment]
the default local.py file is wrong. Please delete it and add the one in the documentation. This module is only used in development. Also be careful, the value debug is True, but it must be for security to be set to false.

**Comment by BillCorey** [comment]
Thanks mwolff44. I tried your suggestion (replaced local.py file) but now have a new error when I use venv:

bil@freesw: /usr/local/venv/pyfreebilling$ source ../bin/activate
(venv) bil@freesw: /usr/local/venv/pyfreebilling$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management

Is there support for this new version? I am trying to follow the instructions but have hard time. How can I overcome this error? thanks again.

**Comment by mwolff44** [comment]
did you install requirements ? could you post the result of this command : `pip freeze`

**Comment by BillCorey** [comment]
Here is the output of "pip freeze" command:
Thanks again

boto==2.34.0
certifi==2017.7.27.1
chardet==3.0.4
colorama==0.3.2
crcmod==1.7
Cython==0.27.3
diff-match-patch==20121119
Django==1.11.7
django-admin-honeypot==1.0.0
django-admin-tools==0.8.1
django-appconf==1.0.2
django-axes==3.0.3
django-bootstrap-pagination==1.6.3
django-bootstrap3==9.0.0
django-braces==1.12.0
django-chroniker==1.0.8
django-countries==5.0
django-crispy-forms==1.6.1
django-currencies==0.4.0
django-datetime-widget==0.9.3
django-extensions==1.9.8
django-filter==1.0.4
django-import-export==0.6.1
django-mathfilters==0.4.0
django-migrate-sql==0.1.1
django-model-utils==3.0.0
django-qsstats-magic==1.0.0
django-queryset-csv==1.0.0
django-render-block==0.5
django-solo==1.1.2
django-tables2==1.12.0
django-templated-email==2.2.0
enum34==1.1.6
et-xmlfile==1.0.1
feedparser==5.2.1
FreeSWITCH-ESL-Python==1.2
future==0.16.0
futures==3.2.0
gax-google-logging-v2==0.8.3
gax-google-pubsub-v1==0.8.3
gcloud==0.18.3
google-compute-engine==2.7.2
google-gax==0.12.5
googleapis-common-protos==1.5.3
grpc-google-logging-v2==0.8.1
grpc-google-pubsub-v1==0.8.1
grpcio==1.8.1
html5lib==0.999
httplib2==0.10.3
idna==2.6
jdcal==1.3
Markdown==2.6.9
netaddr==0.7.19
netifaces==0.10.6
numpy==1.13.3
oauth2client==4.1.2
odfpy==1.3.5
openpyxl==2.4.8
ply==3.8
protobuf==3.5.0.post1
psutil==5.4.1
psycopg2==2.7.3.2
pyasn1==0.4.2
pyasn1-modules==0.2.1
pyfreebilling==1.7.0
pystan==2.17.0.0
python-dateutil==2.6.1
python-stdnum==1.7
pytz==2017.3
PyYAML==3.12
requests==2.18.4
rsa==3.4.2
six==1.11.0
tablib==0.12.1
toposort==1.5
typing==3.6.2
unicodecsv==0.14.1
urllib3==1.22
vatnumber==1.2
virtualenv==15.1.0
xlrd==1.1.0
xlwt==1.3.0

**Comment by mwolff44** [comment]
OK. It seems good. Could you post the local.py file (take care to mask password and key) ?
Could you also post all error messages ?
Thx

**Comment by mwolff44** [comment]
As i have got no news, i think it os ok now. I close it
