### ISSUE TITLE
django-currencies package issue

### ISSUE THREAD

**Issue by mwolff44** [mwolff44/pyfreebilling#106]
The package https://github.com/panosl/django-currencies seems to not be compatible with django 10. Remove it and currency management ?

**Comment by liveincan** [comment]
FYI:
python manage.py updatecurrencies displays: ImportError: cannot import name NoArgsCommand

According to Django Document (https://docs.djangoproject.com/en/1.11/releases/1.8/), the class NoArgsCommand is now deprecated and will be removed in Django 1.10. Use BaseCommand instead, which takes no arguments by default.

**Comment by mwolff44** [comment]
yes, i know. I will remove this package in next release. You skip the updatecurrencies step !

**Comment by liveincan** [comment]
Hi Matt, I think I may have fixed this issue:
  File "/usr/local/venv/local/lib/python2.7/site-packages/currencies/management/commands/updatecurrencies.py"
line 7:
changed: from django.core.management.base import NoArgsCommand
To: from django.core.management.base import BaseCommand

line 20:
Change: class Command(NoArgsCommand):
To: class Command(BaseCommand):

Finally, installed openexchangerates
pip install openexchangerates

Result:
Rates last updated on 2018-02-23 12:00:00
All currencies based against USD
Base currency u'USD' does not exist! Rates will be erroneous without it.

I guess this message will disappear once I setup USD as base currency. Will this solve the issue?

**Comment by mwolff44** [comment]
The system uses currency only for information. There is no calculation. The best way is to remove it (i do not think that it is maintained anymore).
Forget the command updatecurrency

**Comment by liveincan** [comment]
I was hoping this would work as we are constantly converting between USD and CAD. Thanks for your help.
Great product.
