### ISSUE TITLE
hardcoded SIP port

### ISSUE THREAD

**Issue by acheck** [mwolff44/pyfreebilling#134]
Currently you define kamailio 'address' table as the view with the following line:

        '  5060 AS port,'

It means that you hardcode 5060 as SIP port of ip authorized gateway.

It's not a good idea - there are a lot of software and hardware SIP gateways which use ports other than 5060

* some gws just use non-standard ports - say 5070 - for both inbound and outbound
* some gws accept inbound calls to 5060 but sends outbound from some other fixed port - e.g. 5061
* some gws accept inbound calls to 5060 but sends outbound from some random port

as a result you should add port field to the DB and GUI or allow ip:port notation of proxy field

**Comment by mwolff44** [comment]
Yes, you are right. I will do it just after releasing 2.0 version.

**Comment by mwolff44** [comment]
Added in master. Thanks for reporting
