### ISSUE TITLE
Missing columns...

### ISSUE THREAD

**Issue by inedkov** [mwolff44/pyfreebilling#14]
installed everything from scratch on Debian 7.8
When I log in to dashboard everything looks fine until I decide to open one of the submenus.
I always get the same error: (with DEBUG enabled)

column company.vat_number_validated does not exist
LINE 1: ...number", "company"."vat", "company"."vat_number", "company"....

All tables exist and are properly installed.

**Comment by mwolff44** [comment]
Hi,
It seems that the database wasn't well created.
What is the result of the commands (in the virtual env) : 
python manage.py syncdb
python manage.py migrate
