### ISSUE TITLE
Interested in resellere support?

### ISSUE THREAD

**Issue by 416c65** [mwolff44/pyfreebilling#145]
Would you be interested in extending pyfreebilling with reseller support? do you have any plans? I'm planning to implement it, do you have any advice to share?

**Comment by mwolff44** [comment]
It is really interesting. I will add it, but before i want to add others functionalities.
Feel free to talk about this on irc.
We first need to define specs.

**Comment by mwolff44** [comment]
The work is in progress. The next version will integrate many changes that permit the integration of reseller functionalities.

**Comment by thought365** [comment]
when the next version will be release ?

**Comment by mwolff44** [comment]
I will publish a note when It is OK. It will be released when there is no remaining bugs !
