### ISSUE TITLE
How could I install project on local machine using virtualenv 

### ISSUE THREAD

**Issue by tarek-aec** [mwolff44/pyfreebilling#15]

**Comment by mwolff44** [comment]
Hi, check the documentation available on the website : http://www.pyfreebilling.com
Regards

**Comment by tarek-aec** [comment]
I want run project as python manage.py runserver without ssl certificate, may I ?
thank you again

**Comment by mwolff44** [comment]
Hi,

For many reason you can not do it. You need use a web server like apache.

BR

Mathias
