### ISSUE TITLE
kamailio failing acc sql inserts

### ISSUE THREAD

**Issue by freddy36** [mwolff44/pyfreebilling#159]
currently the kamailio acc module fails to insert an accounting statement after a successful call:
```
ERROR: db_postgres [km_dbase.c:290]: db_postgres_submit_query(): 0x7f68ccced348 PQsendQuery Error: ERROR:  syntax error at or near ";"
LINE 1: ...lid,sip_code,sip_reason,time,time_attr,time_exten,;attempt,s...
                                                                                                             ^
Query: insert into acc (method,from_tag,to_tag,callid,sip_code,sip_reason,time,time_attr,time_exten,;attempt,src_ip,calling_num,called_number,sipCode,sipReason ) values ('INVITE','pe2Z0p17QNX9e','2Kr3jKSvpQQcj','16715364-4463-4576-aa37-5a00cd616915','200','OK','2018-04-12 15:20:04',1523546404,171581,'','','','','','')
```

It looks like freeswitch CDRs are used for the accounting and the acc table doesn't exists.
I assume the acc module isn't supposed to be loaded at all?

**Comment by mwolff44** [comment]
At the time being, i am not using kamailio acc, but i am implementing them for help debugging.
I have this working on one server in production. I will check where is the issue.
I will also push the updated db (acc db in pyfreebilling)

**Comment by mwolff44** [comment]
It is done in master now.
