### ISSUE TITLE
LCR confusion

### ISSUE THREAD

**Issue by eightsixeight** [mwolff44/pyfreebilling#165]
Seems all those prefixes are easy to break... in fact never got it working...

the concat function when you lookup rates you concat (c.tech_prefix,r.prefix,'%')
basically customer prefix and rate prefix.. BUT if you dont use prefixes at all then kamailio doesnt even find a destination...

**Comment by mwolff44** [comment]
you have to use prefix for rates. The system works like that.
Thanks

**Comment by eightsixeight** [comment]
i figured it out partially, 
only thing i cannot fix, is if i import my 260,000 rates, doesnt work, 
but if i put manually it works, i think it's a zone issue, but cannot be sure, 


and then i get rates for customer, but not for costs of those rate via sip provider, 

even if they assignes to same billing scheme.

**Comment by mwolff44** [comment]
To import 200000 rates on one shot, you need some RAM available. It is better to split your file or do it with an SQL UPDATE method.

The system works like that : 
customer_sip_account => customer => ratecard => get_rate_from_longest_prefix => gest_lcr_from_matched_ratecard => get_provider_rate_from_longest_prefix

The provider rate needs to be lower than customer rate (you have an option to allow negative margin, but it is disallowed by default)
