### ISSUE TITLE
Billing Time is rounding up

### ISSUE THREAD

**Issue by willianmazzardo** [mwolff44/pyfreebilling#166]
Hi. Im using PyFreeBilling 2.1.1 and I have an issues with billed time.

In example of packet captured, you can see the time of call is 3 secs (between ACK and BYE), but in PyFreeBillling, it shows 4 secs billed.

![captura de tela 2018-12-12 as 15 51 16](https://user-images.githubusercontent.com/6199400/49888431-25220900-fe26-11e8-8045-effe1a31ce59.png)

![billed_time_pyfreebilling](https://user-images.githubusercontent.com/6199400/49888452-30753480-fe26-11e8-9991-65c4d67e08bc.png)

**Expected behavior**
I think it would be possible to define how the round time is made, up or down.
I hope I made myself clear.

Thanks

**Comment by mwolff44** [comment]
Hi,
You have the time in ms in cdr panel. What it is the value for this call ?
Regards
