### ISSUE TITLE
Kamailio Database Is not Created.

### ISSUE THREAD

**Issue by amitiyer** [mwolff44/pyfreebilling#169]
Hello, I have installed Pyfreebilling on debian 8 with multiple IP's as mentioned in the doc and kamailio does not seem to start, after checking the logs kamailio cannot find the database "kamailiopyfb" then i checked the Database after logging in psql and i can see only pyfreebilling DB. Kamailio DB is missing, I also searched the system for the kamailio sql file but could not find it. Can you please let me know how do i create and populate the kamailio DB ?

Thanks.

**Comment by amitiyer** [comment]
I am using V2.2.2 as it is mentioned in the website installation steps.

Below is the kamailio-local.cfg.

`#!define DBURL "postgres://pyfreebilling:admin@127.0.0.1:5432/kamailiopyfb"
#!define DBPYFBURL "postgres://pyfreebilling:admin@127.0.0.1:5432/pyfreebilling"
## DBURL and DBPYFBURL must have the same value. Config will be cleaned !

#!substdef "!MY_IP_ADDRESS!192.168.1.71!g"
#!substdef "!MY_IP_ADDRESS_INTERNAL!192.168.1.71!g"
#!substdef "!MY_IP_ADDRESS_EXTERNAL!192.168.1.71!g"

debug=2

#!define WITH_ANTIFLOOD`

**Comment by mwolff44** [comment]
Change this line `#!define DBURL "postgres://pyfreebilling:admin@127.0.0.1:5432/kamailiopyfb"` by this one `#!define DBURL "postgres://pyfreebilling:admin@127.0.0.1:5432/pyfreebilling"`

I merged the two DB long time ago !

**Comment by amitiyer** [comment]
understood.

**Comment by amitiyer** [comment]
when will version 3 be available ?

**Comment by mwolff44** [comment]
you can try it now. But there is not prepaid for the moment and the reporting part have to be rewritten
