### ISSUE TITLE
Is mod_spidermonkey still required since mod_v8 has replaced it?

### ISSUE THREAD

**Issue by danry25** [mwolff44/pyfreebilling#18]
In Freeswitch v1.4 it appears languages/mod_spidermonkey has been replaced by mod_v8 and has been removed, I'm unsure if mod_v8 is a full drop in replacement but if it is I think we may need to update the docs.

**Comment by mwolff44** [comment]
you can drop it, it is not used !

**Comment by mwolff44** [comment]
i correct the docs
