### ISSUE TITLE
Install Guide needs an update

### ISSUE THREAD

**Issue by tcreek** [mwolff44/pyfreebilling#181]
For the guide located at:

https://www.pyfreebilling.com/knowledge-base/installation/

Here are some areas of concern:

Title indicates install is for Ubuntu, but is for Debian version 8. Debian 8 is End of Life
Sip server installation: Repo info outdated, and Kamailio is now on version 5.4 with repo support for Debian 10  Buster 
SBC installation:Repo info also outdated, and FreeSwitch is now on version 1.10 with repo support for Debian 10 Buster. Also minor setup changes.
Web server install -> install python virtualenv: For command "virtualenv venv" the option "--no-site-packages" is no longer valid.
Web server install -> activate it : source venv/bin/activate has issues
Pyfreebilling installation -> python manage.py collectstatic (answer 'yes') throws an error "-bash: syntax error near unexpected token `(" but will execute without (answer 'yes')

I guess I will stop here. I am assuming the last error is because it is probably using python 2 when version 3 has started to become common.

**Comment by mwolff44** [comment]
Hi, 
The guide is for PyFreeBilling v2 that does not support kamailio 5.4 and is using python 2 version.
The PyFreeBilling version 3 is now in beta test and support Kamailio 5.4 and debian 10 (ubuntu 20.04 ...) and python 3 (only 3 !). If you want to test, you have the docker installation guide available. 
Regards

**Comment by tcreek** [comment]
The guide for docker seems problematic also.

https://www.pyfreebilling.com/knowledge-base/how-to-deploy-pyfreebilling-with-docker/

It does not even state where to exactly obtain version 3 (Who all knows it is on GitHub?) Thought I do see it in the branches as "3.0-dev."

In addition, looking, I do not see a needed Docker Compose file in the 3.0-dve branch.

Maybe clarify that in the Docker guide?

**Comment by mwolff44** [comment]
it is normal that the folder, nor file  /.envs/.production/... does not exist, as it depends on each installation. You have to create it like any project working with environment variables and docker.

**Comment by tcreek** [comment]
But your documentation states the opposite  , " this is what we generate for you:"
Then proceeds to show an image of a directory tree and files.

Maybe can be a little more precise on what is needed for those who are not fully versed with Docker?

Thanks

**Comment by mwolff44** [comment]
PyFB works with Kamailio 4 branch only. You can use centos if you want a compatible OS maintained.
PyFB v2 will not have new features, only v3. The architecture is different, more efficient and easier to maintain.

**Comment by mwolff44** [comment]
i will update the v3 tuto

**Comment by alpharde** [comment]
Any update on this?

**Comment by mwolff44** [comment]
Not now, as it is not ready for production ! For this purpose, only the v2 is OK now.

**Comment by alpharde** [comment]
Kamailio 4 is way outdated and has a few security issues by now, I guess it's better to just wait then.

**Comment by mwolff44** [comment]
I close the ticket. I will publish a post when the v3 is ready for production.
To discuss, it is better to use our matrix room.
