### ISSUE TITLE
installing on virtual machine

### ISSUE THREAD

**Issue by arsenieciprian** [mwolff44/pyfreebilling#185]
Hi. 
Can u please provide one small tutorial for installation on to virtual machine debian .
Thank you for your great work

**Comment by mwolff44** [comment]
Hi,
The installation doc is in WIP (I am working on automatic install script these last days.)
This is the link https://github.com/mwolff44/pyfreebilling/blob/master/docs/getting-started.en.md
The script is pks.
Regards
Mathias

**Comment by arsenieciprian** [comment]
thank you , it will be awsome if u could add billing features to this project based on cgrates

**Comment by mwolff44** [comment]
I will have a look to cgrates API.
do you use it ?

**Comment by arsenieciprian** [comment]
i m not using-it but verry large operators do and is verrrrrry fast and can handle huge capacity and verry eficient and is compatible with kamailio and many other switches also can support portability (LNP)(MNP) witch is verry important to me

**Comment by mwolff44** [comment]
I started a new discussion relative to cgrates integration. I close this ticket.
