### ISSUE TITLE
Toggle disable in LCR for carriers

### ISSUE THREAD

**Issue by iaoakes** [mwolff44/pyfreebilling#92]
It would be useful to temporarily disable a carrier from the LCR vs deleting and having to add again. Sometimes you want to test a specific carrier vs having to remove all but one, or create an lcr just for the carrier.

**Comment by mwolff44** [comment]
I am changing the way lcr work. It will be routing rules.
I integrate your idea.

**Comment by mwolff44** [comment]
done in the future release
